# Generated by Django 4.2.7 on 2024-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default=' ', upload_to='img')),
            ],
        ),
    ]
