# Generated by Django 4.2.7 on 2024-01-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
