# Generated by Django 4.2.7 on 2024-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pamt',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='pname',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
