# Generated by Django 4.2.7 on 2024-01-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_order_amount_alter_order_pamt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pamt',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname',
        ),
    ]
